### ISSUE TITLE
support for XP

### ISSUE THREAD

**Issue by andika207** [dragonfruitnetwork/OnionFruit#1]
I can't believe I am opening the issues' box.
I want to know if there is a legacy version of this utility compatible with Windows XP

thanks

**Comment by aspriddell** [comment]
with the libraries onionfruit uses (mainly telerik), unfortunately not. The tor browser needs windows 7 or higher, so I'm assuming the tor bundle needs that too.

We probably won't be adding any support for users running older versions of windows as the compatibility issues are too severe.
