### ISSUE TITLE
False Tor Disconnected Status

### ISSUE THREAD

**Issue by evilthreads669966** [dragonfruitnetwork/onionfruit#11]
After toggling OnionFruit to be enabled, a status page displays saying I am not connected to Tor but shows for example country Germany. However, if I click Tor Disconnected it goes to https://check.torproject.org/. There it says I am connected to Tor. This happens every time but did not used to happen in the past. I also confirmed through IPChicken as I have a different IP address after disabling the toggle and then re-enabling OnionFruit. Note: I am located in the United States.

**Comment by aspriddell** [comment]
Thanks for reporting this. It's most likely that you've been connected to the network via a new exit gateway that cloudflare is yet to add to their database. https://dragonfruit.network/onionfruit/status checks the connection by the cloudflare-added country header, which tor has it's own dedicated code (`T1` if you're interested). If the country is displaying differently then I wouldn't worry - a reconnect or a custom pick of a country should sort it out.

That said if it keeps happening you can disable the page in the settings (under landing pages)

**Comment by evilthreads669966** [comment]
``` If the country is displaying differently then I wouldn't worry - a reconnect or a custom pick of a country should sort it out.```
My country should not be displaying. It is displaying the country for my exit node. Which is correct. I am not complaining about anything. I am just simply letting you know that your status page is displaying the opposite status with the correct country.

Also, I assume you're updating your backend and not client? As I see no way for updating the client.

**Comment by evilthreads669966** [comment]
Ah yes as you have labeled it area:website obviously. Excuse me.

**Comment by evilthreads669966** [comment]
This issue should be closed as it is working now.

**Comment by aspriddell** [comment]
ok - thanks for responding, it helps :)

**Comment by evilthreads669966** [comment]
I'm sorry. It appears that the issue has persisted and is not fixed.

**Comment by aspriddell** [comment]
what country shows on the main page? (for example for me it would be Japan)

![image](https://user-images.githubusercontent.com/10289119/108098157-f265a200-707a-11eb-8fbb-4f8131c843a8.png)

**Comment by evilthreads669966** [comment]
It showed random but I believe it was Japan on the disconnected status page

**Comment by evilthreads669966** [comment]
I restarted and it works and is now showing correct status of connected.

**Comment by evilthreads669966** [comment]
I found in the settings that I can change the landing page. I'll just change it to check tor

**Comment by aspriddell** [comment]
yeah, was about to say - I'll keep monitoring and report to cloudflare if it keeps happening. as mentioned before, you're probably being routed through some newer servers with IP addresses not picked up yet, so it's showing as disconnected.

**Comment by evilthreads669966** [comment]
Ok thanks.

**Comment by aspriddell** [comment]
while i've been messing with the obfs4 and meek transports, I too noticed that they always show up as disconnected, regardless of what bridges are used. I'm going to reopen this to track the site using a second check, where if it's disconnected it'll send a DNS lookup to `[ipaddress-reversed].dnsel.torproject.org` and check the response.

**Comment by evilthreads669966** [comment]
I got this in my email. I'm currently working on another project. If you're looking for someone to join this project then contact me on telegram evilthreads669966

**Comment by evilthreads669966** [comment]
https://t.me/evilthreads669966

**Comment by aspriddell** [comment]
no worries, i remembered that there was an issue tracking this, so was just re-using it (also was hoping it'd ping you so you'll know we're looking into it further)

**Comment by aspriddell** [comment]
should be better with the latest yuna update
