### ISSUE TITLE
Access torrc in OnionFruit

### ISSUE THREAD

**Issue by TorFan888** [dragonfruitnetwork/onionfruit#14]
Not knowing if torrc is the place to do it, I want to exclude a domain from going through Tor.

	Something like:
http://www.domai*
	excluded from Tor

With telnet access, I could change things on the fly.

And possibly a switch to make OF tor.exe use a different torrc file, overriding it's own.

tor --controlport 9051
In my case, port 9051 would only be used for this.

This would allow me access to sites that don't like Tor exit nodes.

I've been in email conversation about this with DragonFruit Network. They suggested this approach.

**Comment by aspriddell** [comment]
Torrc doesn't look to have a way to exclude a domain specifically, it can only do by tor node country. The best bet would be to change this box and fill the domains you want excluded in there. Not sure if you can use wildcards but it _does_ say that it'll exclude if it starts with the entry (so just drop the * off the end)

![image](https://user-images.githubusercontent.com/10289119/114191318-302ccb80-9944-11eb-9e4b-458a9d2be981.png)

as far as the torrc file override, that won't be happening. the point of OF is to make it easy to connect to tor with things like country configs, etc. allowing user configs removes all this functionality and you'd be better off booting tor.exe and changing your proxy settings manually

**Comment by TorFan888** [comment]
Albie, that does work (w/o wildcard). Had to toggle proxy server off/on,
and logoff/on my now non-proxied site.

Didn't try wildcard.

So, I'm no worried about accrss to torrc, but it could be useful as an
'advanced' feature.

Thanks!

**Comment by aspriddell** [comment]
excellent, glad to hear :)

if you have any ideas/suggestions/whatever, feel free to create another issue (or email if it's something that shouldn't be public)
we'll be glad to hear you out
