### ISSUE TITLE
adding tor control interface

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/onionfruit#15]
I've thought about @TorFan888's proposal in #14 and while OF is unable to provide access to the torrc file (because it could render configs useless or cause misconfigs), we can try to allow advanced users to mess with the system, and if they break it then it's their fault.

this is where i'm up to:

![onionfruit-ipc-alpha](https://user-images.githubusercontent.com/10289119/114263659-da593180-99de-11eb-9c29-73876fb9da81.gif)

still need to put some form of disclaimer saying this is (like SecurDNS) also experimental and as such will be opt-in only.

In the future I might look at randomly generating a password per session to stop other clients tapping in and potentially reducing the security the tor network creates (by changing hop count, etc.) and the main feature was to create some sort of connection that would allow us to send pre-defined commands to regenerate circuits, change countries on-the-go, etc.

@TorFan888 this sound like something you'd be interested in having added?

**Comment by TorFan888** [comment]
Albie, looks like a great idea! If you put something together you'd loke
tested, I'll help.

**Comment by aspriddell** [comment]
thanks, it'll probably go in cutting edge releases (under the feature tab in settings) so feel free to test/report feedback once it's finished.

Be aware that I'm writing this to have a randomly generated password to force users to use the built in client, and some settings like port changes will be intercepted and dropped by the client (to make sure OF still works properly).

**Comment by TorFan888** [comment]
OK, I'll watch for it.

**Comment by aspriddell** [comment]
@TorFan888 the update has been published. you can update to pre-release versions by going to settings -> features -> cutting edge releases then restarting the app (it will then update, at which point you need to restart the program again)

**Comment by TorFan888** [comment]
2nd reply.

I loaded the torrc file in a text editor and found

HashedControlPassword
16:A7E1F52597FEC9D660D70B5229D061C030996BA29B6A7C12E6ECAB7D8F

so I tried

authenticate 16:A7E1F52597FEC9D660D70B5229D061C030996BA29B6A7C12E6ECAB7D8F

I bet I need to unhash that, right? Don't know how.

**Comment by TorFan888** [comment]
Thank you. Here's what's happening:

I start PuTTY and load the connection profile for torrc.

localhost 9051

I get a terminal window. I input
authenticate ""

and it's rejected.

Image attached.

**Comment by aspriddell** [comment]
@TorFan888 as i mentioned above:

>Be aware that I'm writing this to have a **randomly generated password** to **force users to use the built in client**, and some settings like port changes will be **intercepted and dropped** by the client (to make sure OF still works properly).

**Comment by TorFan888** [comment]
I must be misunderstanding. Am I supposed to be able to access Tor now? If
so, how do I get the password?

Also, I might have missed something...

**force users to use the built in client**

What client?

**Comment by aspriddell** [comment]
you can access the console by connecting, then right clicking the OF main window then select `Tor Control`

it'll bring up the window as shown in the OP and you can send the commands

**Comment by TorFan888** [comment]
OK, I see how it works now. I'll play around with it and see if I can
break it.

Thanks

**Comment by aspriddell** [comment]
any bugs/issues/feedback on this can be opened as a separate issue. closing
