### ISSUE TITLE
Settings dialog does not display

### ISSUE THREAD

**Issue by ilike2win** [dragonfruitnetwork/onionfruit#19]
Although Settings button is visible on main program window, clicking on it does not spawn a Settings dialog box/window.  Likewise, although Settings is available in a floating menu when right-clicking on the main program window, this also does not spawn a Settings dialog  box/window.
Please advise if some accessory components are needed to get this functionality to work.
Thanks!

**Comment by aspriddell** [comment]
are you trying to open this window while connected? if the country list is greyed out you should not be able to open the settings

**Comment by ilike2win** [comment]
Thanks for your quick response and clarification.  I could have sworn that I tried to open settings when disconnected yesterday and it did not work, but it did today.
>>issue closed, thanks.
