### ISSUE TITLE
add option to block microsoft telemetry servers while connected

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/onionfruit#20]
not 100% sure about the effectiveness of this but it's as the title says: while you're connected, Microsoft will be unable to receive their "telemetry" updates. This can be useful because:

1. telemetry updates likely can ID your machine, and that means they can tie your machine to a tor ip address
2. because of this, blocking it from sending means they are less likely to get your ip (depends on how aggressive they are)
3. it's _really_ simple to implement (although uses a bit of a hack)

the only reason against it is it's scheduled so... it'll run at some point and still send the data to a collection server.

would be cool to extend this to delete the diagnostic data before running and after, which would kinda resolve the drawback mentioned above (although this might be pushing slightly out of scope for a "VPN")

edit: the folder that holds this "diagnostic" data is very well protected and as a result would 100% need to kill some processes and change ownership of the folder to allow us to delete it, therefore it will require admin to use this, like SecurDNS)

opinions on this are very welcome

**Comment by aspriddell** [comment]
this could be helpful when adding the feature. It'll retrieve a list of processes onionfruit will need to kill to delete the diagnostic files
https://stackoverflow.com/a/20623311/12267879

**Comment by DNS** [comment]
To kill CompatTelRunner.exe immediately:
https://github.com/adolfintel/Windows10-Privacy/issues/4

**Comment by aspriddell** [comment]
Going to close this one as the diagnostic folder would need deletion and then the app needs to be run as admin and has the potential to produce undefined and unreproducable behaviour.
