### ISSUE TITLE
Add support for Android & iOS

### ISSUE THREAD

**Issue by PCUser2021** [dragonfruitnetwork/onionfruit#25]
Please support Android & iOS.

**Comment by aspriddell** [comment]
not going to happen. sorry.

you'll need to use the official apps for this

**Comment by aspriddell** [comment]
to provide more of an explanation:

- our iOS toolkit is limited
- we don't intend on purchasing an app store membership
- the [app store policy](https://developer.apple.com/app-store/review/guidelines/#vpn-apps) regarding VPNs is strict, and we would likely fail on one of the points there, blocking us from release

**Comment by PCUser2021** [comment]
> to provide more of an explanation:
> 
> * our iOS toolkit is limited
> * we don't intend on purchasing an app store membership
> * the [app store policy](https://developer.apple.com/app-store/review/guidelines/#vpn-apps) regarding VPNs is strict, and we would likely fail on one of the points there, blocking us from release
> 
> another thing to understand is onionfruit is **not** a vpn, but rather a locally hosted proxy that gives a similar effect without the driver installs. android has an app called orbot that can function as a vpn, and there are a few tor browsers on iOS that you can download for free

We don't want Tor browsers, we want Orbot (that is the official Tor for Android) for iOS.

**Comment by aspriddell** [comment]
and for the reasons above (the bullet points) and the fact that I almost singlehandedly manage over 10 different apps, that is not going to be coming from me in the near future
