### ISSUE TITLE
OFC 2021.818 doesn't connect

### ISSUE THREAD

**Issue by PCUser2021** [dragonfruitnetwork/onionfruit#26]
OK
Tested on 2 systems:
My second system: Win 10 x64 Pro
Tor connected, proxy disabled.
Doesn't work at all.
My default system at least shows it's connected.

**Comment by aspriddell** [comment]
i'm going to guess both logs are as you provided in the last issue and that they worked with no issue. it's to do with your browser settings or something. as i said, nobody can diagnose this because nobody can replicate.

**Comment by aspriddell** [comment]
try disabling cutting-edge builds, uninstalling the program and install the latest stable version (2021.810) and test with that. if that works, respond because that's a regression, if not, use the tor browser because that hacks around your computer's misconfiguration.
