### ISSUE TITLE
App says connected, but browser does not

### ISSUE THREAD

**Issue by soshimee** [dragonfruitnetwork/onionfruit#28]
**Please read [this wiki entry](https://github.com/dragonfruitnetwork/onionfruit/wiki/Reporting-Issues)** and remove this line.

**Describe the bug**
When I try to connect, it takes several seconds and it says tor connected, but it also opens a browser window that says tor isn't connected and I can see my actual country instead of country I chose.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect
2. Doesn't work

**Expected behaviour**
The app should at least know that it isn't actually connected. Better yet it should actually connect.

**Screenshots**
![image](https://user-images.githubusercontent.com/45235204/150149549-10ae6df5-2d58-4abf-ba76-1665a5453ccf.png)

**Logs**
See [this wiki entry](https://github.com/dragonfruitnetwork/onionfruit/wiki/Reporting-Issues) on how to get logs
[OnionFruit-2022.1.19-session1.txt](https://github.com/dragonfruitnetwork/onionfruit/files/7897826/OnionFruit-2022.1.19-session1.txt)

**Comment by aspriddell** [comment]
you're using firefox, so you might need to check your [proxy settings](https://support.mozilla.org/en-US/kb/connection-settings-firefox) are set to `Use system proxy settings`

**Comment by soshimee** [comment]
It wasn't really Firefox that I was using, but I found an equivalent option, and it works now, thanks.
