### ISSUE TITLE
Option to block all non tor connections

### ISSUE THREAD

**Issue by distrair** [dragonfruitnetwork/onionfruit#29]
Tallow have option to block all non tor connections, can you add this too? Or change the way its connect to network so all apps will use tor?

**Comment by aspriddell** [comment]
onionfruit sets the system proxy so if the app won't detect/use it there's not a lot the app can do. Yes, onionfruit could create a vpn and go down that route but that now requires admin and breaks all current installations so that is unlikely to happen.

**Comment by distrair** [comment]
How about add this as optional (button in the settings), so there will be two modes of connecting to the tor network?

**Comment by aspriddell** [comment]
As I mentioned in the previous comment, it would break all current installations and is not in the scope of the app. If you want a system that forces all traffic through a tunnel, you should use a VPN. OnionFruit is supposed to target browsers which 99% will respect the system settings.

**Comment by distrair** [comment]
Alright, I still hope that it will be added in the future.
