### ISSUE TITLE
The proxy doesn't work

### ISSUE THREAD

**Issue by j8xx** [dragonfruitnetwork/onionfruit#35]

**Comment by aspriddell** [comment]
The logs have this line in which is what I guess is the issue:

```
2023-01-07 23:48:16 [dbg] Jan 07 23:48:16.000 [warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed]. [436 similar message(s) suppressed in last 300 seconds]
```

As you mention blocked sites, are you using a bridge to connect to tor? If you're using obfs4, I'd suggest getting some new bridge lines and trying them

**Comment by j8xx** [comment]
no actually i dont use any bridges.
on tor i used to use snowflake which worked well enough but the proxy on onionfruit made it so I didn't need to use snowflake anymore. but now even with snowflake the error still persists.

**Comment by aspriddell** [comment]
Another line from the log file is 

```
[notice] Opened Control listener connection (ready) on 127.0.0.1:9052
```

I'm guessing the errors are coming from trying to connect to the control port instead of the socks port.
If you get this error again, try opening the proxy settings and manually change the port 9052 to 9051 and reload the browser.
