### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [dragonfruitnetwork/onionfruit#37]
Does this work with Win 7?

If the latest version doesn't, what was the last version to work?

Thanks

**Comment by aspriddell** [comment]
It'll most likely not work unless you have the very latest version of windows 7, but even then there's no guarantees.

If you've got a windows 7 machine you want to try it on, feel free to try and see what happens, but we won't be able to fix issues that are directly due to old/unsupported systems.

**Comment by harryray33** [comment]
Thanks, I'll give it a try. Is there anywhere I can download an older version so that I can try that out as well?

**Comment by vadimlitvinenko87** [comment]
You too lazy to try out yourself what you need (OnionFruit™ Connect 2022.120.0)

**Comment by aspriddell** [comment]
Closing as there's no more to be said on this matter, an open-source onionfruit is in the works but it uses .NET 8 which supports windows 10 or later so windows 7 will not be supported i'm afraid
