### ISSUE TITLE
how do I get this to work with utorrent?

### ISSUE THREAD

**Issue by BotMasterGod** [dragonfruitnetwork/onionfruit#38]
p2p programs are blocked by this building's router, so I figured dragonfruit could be used to bypass it. 

I saw that this could be used as a vpn, and I need a fully free vpn with no cap limit to work with torrents, so I thought this was it.

But no matter what I do, it's not working.

help?
![proxy](https://user-images.githubusercontent.com/112343990/229344531-f9092133-f2d0-4c50-ac7c-f412333c2bd1.PNG)

**Comment by aspriddell** [comment]
From what I understand, torrenting over tor is not recommended as you're going to hit some issues with performance. [This article](https://blog.torproject.org/bittorrent-over-tor-isnt-good-idea/) also says that despite the proxy settings being applied, some clients ignore them and that's where the direct connections are occurring from (which are being blocked).

You might find that using other clients may yield better results, or alternatively consider investing in a proper vpn like surfshark or a web-based torrenting service. Apart from that, there's not a lot we can do on our end as the issue ultimately lies with the torrent client.

**Comment by BotMasterGod** [comment]
> From what I understand, torrenting over tor is not recommended as you're going to hit some issues with performance. [This article](https://blog.torproject.org/bittorrent-over-tor-isnt-good-idea/) also says that despite the proxy settings being applied, some clients ignore them and that's where the direct connections are occurring from (which are being blocked).
> 
> You might find that using other clients may yield better results, or alternatively consider investing in a proper vpn like surfshark or a web-based torrenting service. Apart from that, there's not a lot we can do on our end as the issue ultimately lies with the torrent client.

"fully free vpn" I got no money. I need something completely free, no trial crap, no fee crap, etc.

thanks for the article, if you can recommend something specific that is 110% free (AND STAYS FREE), I would love to know it please.

**Comment by aspriddell** [comment]
sorry, but you'll have to look for this yourself - it's likely you'll struggle to find a decent service that's fast enough.

Closing this as the original question was resolved
