### ISSUE TITLE
Https tor proxy

### ISSUE THREAD

**Issue by koljanich** [dragonfruitnetwork/onionfruit#39]
**Describe the bug**
Some programs, like Android Studio, need Http/s proxy to download gradle. Please open in program Http/s proxy port.

**Expected behaviour**
I expect you open it! I really need this!

**Comment by aspriddell** [comment]
It already does? OnionFruit sets the system proxy to localhost:9050 (or closest available port) so if you check the app settings and set it to use the system proxy then there should be no issue.

**Comment by koljanich** [comment]
![изображение](https://user-images.githubusercontent.com/10668288/235957961-6957e942-50e9-4709-9f1b-caf08cfc1745.png)
![изображение](https://user-images.githubusercontent.com/10668288/235958344-f4e1b306-0757-433f-8977-84abb6c5e975.png)

**Comment by koljanich** [comment]
Same result

![изображение](https://user-images.githubusercontent.com/10668288/235960650-76da8f05-c648-4fe5-a252-95bebce9a803.png)
![изображение](https://user-images.githubusercontent.com/10668288/235960735-a658b3a6-88a2-4d02-a63e-1b45241a8e82.png)

**Comment by koljanich** [comment]
Add args to org.gradle.jvmargs in gradle.properties
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=9050

Nothing to change... Same error

**Comment by aspriddell** [comment]
in that case there's not a lot more I can do, it's down to the program itself to support system proxies, so you might need to take this up with android studio/gradle (as in their program doesn't support socks5 proxies, not that it doesn't support onionfruit)
