### ISSUE TITLE
OnionFruit Connect portable

### ISSUE THREAD

**Issue by skarsgal** [dragonfruitnetwork/OnionFruit#4]
Hi,
do You can create a portable version of OnionFruit Connect for both 32 and 64 bit ?
If possible in PAF format like builds on site PortableApps.com.
Thanks.

**Comment by aspriddell** [comment]
theoretically we _could_, but at the moment there is simply not a high enough demand for it. OnionFruit is designed to be always up-to-date and by adding multiple "flavours" would make releasing updates harder and more time-consuming, as portable apps may not be able to automatically update. The installer doesn't need admin - it simply copies itself to the `%localappdata%` folder and manifests from there.

Tor is 32-bit and so is the OnionFruit Client. There is absolutely no need for a 64-bit version of the client, as it will have zero benefits, and (as mentioned above) would slow updates and development.
