### ISSUE TITLE
Do not configure top if path contains national characters

### ISSUE THREAD

**Issue by Kolya772099** [dragonfruitnetwork/onionfruit#40]
**Please read [this wiki entry](https://github.com/dragonfruitnetwork/onionfruit/wiki/Reporting-Issues)** and remove this line.

**Describe the bug**
Tor long connecting and not connect.

**To Reproduce**
Steps to reproduce the behaviour:
1.  onionfruit installed in default path:
C:\Users\Николай\AppData\Local\OnionFruitConnect\
2. Tor ignore all settings.
3.  Tor output:
```
C:\Users\Николай\AppData\Local\OnionFruitConnect\app-2022.1123.0\Tor>tor.exe
May 13 12:46:58.985 [notice] Tor 0.4.7.11 (git-1885fa4d36ea26c1) running on Windows 8 [or later] with Libevent 2.1.12-stable, OpenSSL 1.1.1s, Zlib 1.2.13, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
May 13 12:46:58.985 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
May 13 12:46:59.000 [notice] Configuration file "C:\Users\═шъюырщ\AppData\Roaming\tor\torrc" not present, using reasonable defaults.
May 13 12:46:59.000 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Users\═шъюырщ\AppData\Local\OnionFruitConnect\app-2022.1123.0\Tor\<default>. Is this what you wanted?
May 13 12:46:59.000 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Users\═шъюырщ\AppData\Local\OnionFruitConnect\app-2022.1123.0\Tor\<default>. Is this what you wanted?
```

**Comment by aspriddell** [comment]
Is this being run via the desktop client? If you're just running tor.exe on its own none of the system configuration is going to happen or settings created by the client will be applied.

If you aren't, please use the desktop client to start the tor process, and if you are can you share more details like what version of windows are you using and provide the most recent logs (see the wiki entry link at the top of your issue post that you didn't remove)

**Comment by aspriddell** [comment]
Closing as this is not an onionfruit related issue
