### ISSUE TITLE
How to uninstall the program

### ISSUE THREAD

**Issue by kingparsa1010** [dragonfruitnetwork/onionfruit#44]
Thanks for your good program but there is no unintall.exe or similar things on the program file. how can i completely uninstall it?

**Comment by aspriddell** [comment]
Control panel

**Comment by kingparsa1010** [comment]
thanks man , that was quick!

**Comment by aspriddell** [comment]
Additionally, delete `%LOCALAPPDATA%\DragonFruit Network\OnionFruit` to get rid of additional user data (you'll reclaim approx 10mb)
