### ISSUE TITLE
tor killed - traffic restricted

### ISSUE THREAD

**Issue by fronfron** [dragonfruitnetwork/onionfruit#45]
when i try to connect to with onion fruit it says "tor killed-traffic restricted"
i have already downloaded .net framework and installed it. i runned it as an aministrator and i'm not connected with a proxy

**Comment by aspriddell** [comment]
That means something on your system is causing the app to crash.

Check if you have any antivirus that is blocking the tor process from running (tor.exe) and if not, upload logs (see the wiki for instructions) and we can look into it further.

It also might be due to improperly configured bridge entries, so if you've entered some obfs4 bridge lines into the config try removing them or switching to snowflake and see if it has any effect

**Comment by NiKola-UE** [comment]
As I wrote via 
[this issue, ](https://github.com/dragonfruitnetwork/onionfruit/issues/43), 
antiviruses can report OnionFruit and similar apps and tools as some fraudulent and harmful, which should be addressed in the user manual, unless it has already been done. 






I'm not a developer, but I think maybe the source code of the OnionCat could be used for some improved performance or something like that...

**Comment by Aztec2012** [comment]
Same for me. But how to fix this?

**Comment by aspriddell** [comment]
> One of the authors should answer these questions, but no one has yet.

The answer is posted above. The program monitors the process and triggers this state when tor.exe is killed and was not a result of the user stopping the connection in app. You can easily try this by opening task manager and killing the program yourself.

This means that _something_ on your machines is killing the app. Whether that's a game anti-cheat engine, Microsoft defender, some anti-ransomware or a buggy program on your system we don't know, and can't tell you without any other information. If you're technically minded, you can always try PID profiling but that's out of scope for us.

A good start would be to take a look at what's on your PC and ask yourself "would this program be likely to interfere with other running apps?" - this'll give you an idea of potential suspects.

> OnionCat could be used for some improved performance or something like that

That's not how OnionFruit works. It just boots tor and points your system to it, just like how the official browser works. After completing the connection to Tor, the app just monitors the app for errors and shuts down if there's an issue.

**Comment by NiKola-UE** [comment]
OK, thank you.
