### ISSUE TITLE
BSD: platform Support

### ISSUE THREAD

**Issue by jujubeja** [dragonfruitnetwork/onionfruit#47]
### Release BSD version

[GhostBSD](https://ghostbsd.org/) GhostBSD builds on the robust FreeBSD codebase, A simple, elegant desktop BSD Operating System.

[NomadBSD](https://nomadbsd.org/) NomadBSD is a persistent live system for USB flash drives, based on FreeBSD®.

[MidnightBSD](https://www.midnightbsd.org/) MidnightBSD is a FreeBSD-derived Operating System. A critical goal of the project is to create an easy to use desktop environment with graphical ports management.

**Comment by aspriddell** [comment]
.NET Framework isn't supported on non-windows platforms, and the new version will use .NET 8 which _sort_ of has support but some of the libraries used won't bundle BSD-compatible binaries, in addition to lack of testing environments, small user base, etc.

Once the new version is up, you're free to have a go and get it working but as most users are on other platforms, effort will be focused there. Feel free to reopen once the new version is published if any progress has been made!
