### ISSUE TITLE
Problems with connection in Eastern Europe

### ISSUE THREAD

**Issue by ZdenekBachy** [dragonfruitnetwork/onionfruit#58]
Hello! I have some problems with connection.
Firstly, I try to explain what I did. I installed a program on a laptop with Win10. When I tried to connect, the application froze at 5% and I saw this:
![Снимок экрана (424)](https://github.com/user-attachments/assets/a0961cce-0905-4907-817e-61dcf45cbe0d)
If I change a region and/or settings I have a similar situation. I don't understand, what I can do with it(maybe I do smth wrong?). I'm an amateur in it.

**Comment by coderVi** [comment]
+ Make sure Windows is up to date.

+ Test the network connection.
+ Try the region as Default.

If you have tested everything, we Turks have a very nice saying;

**If it doesn't work, close and open it. It will probably fix it** :)

**Comment by aspriddell** [comment]
This happens when you choose a country combo (entry and exit) that doesn't have enough servers to make a reliable connection. If you select Random or a country with lots of servers (try Germany or US) it should work. Basically the same as @coderVi has posted but with a bit more of an explanation.

If you get the same issue, upload the runtime.log file found in `%localappdata%\DragonFruit Network\OnionFruit\Logs` and I can see if there's anything there.

**Comment by ZdenekBachy** [comment]
Thanks for all the advice! It's really fast! I check network connection, updates, system dates, and other classic points. I rebooted a laptop and my Wi-Fi router. Finally, I repeated it with random countries and with the USA, Germany, and some others, checking logs. Classic view was:

> 2024-12-22 00:59:56.426 +03:00 [DBG] Hosting starting
> 2024-12-22 00:59:56.698 +03:00 [INF] onion.db version null loaded successfully
> 2024-12-22 00:59:56.700 +03:00 [INF] "InterNetwork" GeoIP file to be written to C:\Users\Admin\AppData\Local\Temp\oniondb-1734778700.geoip
> 2024-12-22 00:59:56.700 +03:00 [INF] "InterNetworkV6" GeoIP file to be written to C:\Users\Admin\AppData\Local\Temp\oniondb-1734778700.geoip6
> 2024-12-22 00:59:56.701 +03:00 [INF] GeoIP files already exist, skipping write
> 2024-12-22 00:59:56.704 +03:00 [INF] Application started. Press Ctrl+C to shut down.
> 2024-12-22 00:59:56.704 +03:00 [INF] Hosting environment: Production
> 2024-12-22 00:59:56.704 +03:00 [INF] Content root path: C:\Users\Admin\AppData\Local\onionfruit\current
> 2024-12-22 00:59:56.857 +03:00 [DBG] Hosting started
> 2024-12-22 00:59:59.043 +03:00 [DBG] [tor]: with Libevent 2.1.12-stable, OpenSSL 3.0.15, Zlib 1.3.1, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
> 2024-12-22 00:59:59.044 +03:00 [DBG] [tor]: Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
> 2024-12-22 00:59:59.048 +03:00 [DBG] [tor]: Read configuration file "C:\Users\Admin\AppData\Local\Temp\tmpwgtbdr.tmp".
> 2024-12-22 00:59:59.050 +03:00 [DBG] [tor]: Opening Socks listener on 127.0.0.1:9050
> 2024-12-22 00:59:59.050 +03:00 [DBG] [tor]: Opened Socks listener connection (ready) on 127.0.0.1:9050
> 2024-12-22 00:59:59.050 +03:00 [DBG] [tor]: Opening Socks listener on [::1]:9050
> 2024-12-22 00:59:59.050 +03:00 [DBG] [tor]: Opened Socks listener connection (ready) on [::1]:9050
> 2024-12-22 00:59:59.050 +03:00 [DBG] [tor]: Opening Control listener on 127.0.0.1:9051
> 2024-12-22 00:59:59.050 +03:00 [DBG] [tor]: Opened Control listener connection (ready) on 127.0.0.1:9051
> 2024-12-22 00:59:59.050 +03:00 [DBG] [tor]: Opening Control listener on [::1]:9051
> 2024-12-22 00:59:59.050 +03:00 [DBG] [tor]: Opened Control listener connection (ready) on [::1]:9051
> 2024-12-22 00:59:59.050 +03:00 [DBG] [tor]: Your log may contain sensitive information - you disabled SafeLogging. Don't log unless it serves an important reason. Overwrite the log afterwards.
> 2024-12-22 00:59:59.051 +03:00 [DBG] [tor]: Parsing GEOIP IPv4 file C:\Users\Admin\AppData\Local\Temp\oniondb-1734778700.geoip.
> 2024-12-22 00:59:59.238 +03:00 [DBG] [tor]: Parsing GEOIP IPv6 file C:\Users\Admin\AppData\Local\Temp\oniondb-1734778700.geoip6.
> 2024-12-22 00:59:59.407 +03:00 [DBG] [tor]: Bootstrapped 0% (starting): Starting
> 2024-12-22 00:59:59.407 +03:00 [DBG] [tor]: Starting with guard context "default"
> 2024-12-22 01:00:00.416 +03:00 [DBG] [tor]: Bootstrapped 5% (conn): Connecting to a relay
> 2024-12-22 01:01:24.554 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 10; recommendation warn; host 3F6E66FDA54B0CED35F01A16AF5D034DDDD8D48C at 45.138.16.222:9000)
> 2024-12-22 01:01:24.554 +03:00 [DBG] [tor]: 9 connections have failed:
> 2024-12-22 01:01:24.554 +03:00 [DBG] [tor]:  9 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:01:26.760 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 11; recommendation warn; host 775D0AA34AC2E892CB98596F706DB96E6D49DD7A at 45.94.31.26:443)
> 2024-12-22 01:01:26.760 +03:00 [DBG] [tor]: 10 connections have failed:
> 2024-12-22 01:01:26.760 +03:00 [DBG] [tor]:  10 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:01:31.795 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 12; recommendation warn; host E5293854BEF5F319210CA894B8D365FED578BE7D at 84.247.164.52:8916)
> 2024-12-22 01:01:31.795 +03:00 [DBG] [tor]: 11 connections have failed:
> 2024-12-22 01:01:31.795 +03:00 [DBG] [tor]:  11 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:01:45.617 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 13; recommendation warn; host 7C1A1517C27A0C68329D84D94372E0ACA9390B00 at 185.220.101.200:443)
> 2024-12-22 01:01:45.617 +03:00 [DBG] [tor]: 12 connections have failed:
> 2024-12-22 01:01:45.617 +03:00 [DBG] [tor]:  12 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:01:45.618 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 14; recommendation warn; host 74A910646BCEEFBCD2E874FC1DC997430F968145 at 199.58.81.140:443)
> 2024-12-22 01:01:45.618 +03:00 [DBG] [tor]: 13 connections have failed:
> 2024-12-22 01:01:45.618 +03:00 [DBG] [tor]:  13 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:01:52.859 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 15; recommendation warn; host 9ECF8F065C79FC213A1BF6C1AA2D8CBCC9368F92 at 192.42.116.218:9000)
> 2024-12-22 01:01:52.859 +03:00 [DBG] [tor]: 14 connections have failed:
> 2024-12-22 01:01:52.859 +03:00 [DBG] [tor]:  14 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:02:06.672 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 16; recommendation warn; host 7E33C702C95FB4A3D2C203DB4A40D330C5029D81 at 104.254.130.186:8443)
> 2024-12-22 01:02:06.672 +03:00 [DBG] [tor]: 15 connections have failed:
> 2024-12-22 01:02:06.672 +03:00 [DBG] [tor]:  15 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:02:06.672 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 17; recommendation warn; host 1A25C6358DB91342AA51720A5038B72742732498 at 128.31.0.39:9201)
> 2024-12-22 01:02:06.672 +03:00 [DBG] [tor]: 16 connections have failed:
> 2024-12-22 01:02:06.672 +03:00 [DBG] [tor]:  16 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:02:13.896 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 18; recommendation warn; host 9CD8AC434F90DC1AA7E18D019A34ACEB218E9EA5 at 77.221.159.192:443)
> 2024-12-22 01:02:13.896 +03:00 [DBG] [tor]: 17 connections have failed:
> 2024-12-22 01:02:13.896 +03:00 [DBG] [tor]:  17 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:02:27.729 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 19; recommendation warn; host 568E434F725B7828D17EF2B33C2F5CC84F18FCE3 at 91.219.238.148:9001)
> 2024-12-22 01:02:27.729 +03:00 [DBG] [tor]: 18 connections have failed:
> 2024-12-22 01:02:27.729 +03:00 [DBG] [tor]:  18 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:02:29.050 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 20; recommendation warn; host A38625F86DD9F8DFA2C6CA4D7CB47DB801FBD7E0 at 23.92.34.120:443)
> 2024-12-22 01:02:29.050 +03:00 [DBG] [tor]: 19 connections have failed:
> 2024-12-22 01:02:29.050 +03:00 [DBG] [tor]:  19 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:02:34.957 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 21; recommendation warn; host 7EA6EAD6FD83083C538F44038BBFA077587DD755 at 45.66.35.11:443)
> 2024-12-22 01:02:34.957 +03:00 [DBG] [tor]: 20 connections have failed:
> 2024-12-22 01:02:34.957 +03:00 [DBG] [tor]:  20 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:02:34.957 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 22; recommendation warn; host 9EE1970E1AD558CF0F297537E32A449EB740CB9D at 172.104.243.155:8443)
> 2024-12-22 01:02:34.957 +03:00 [DBG] [tor]: 21 connections have failed:
> 2024-12-22 01:02:34.957 +03:00 [DBG] [tor]:  21 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:02:50.094 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 23; recommendation warn; host B55DF560D234C531BFE623079CF685B4FAF8EDFE at 85.24.237.73:443)
> 2024-12-22 01:02:50.094 +03:00 [DBG] [tor]: 22 connections have failed:
> 2024-12-22 01:02:50.094 +03:00 [DBG] [tor]:  22 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:02:55.999 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 24; recommendation warn; host 4236EA92D6B758A98C5334051C2D88FCB4843CC5 at 85.215.66.179:443)
> 2024-12-22 01:02:55.999 +03:00 [DBG] [tor]: 23 connections have failed:
> 2024-12-22 01:02:55.999 +03:00 [DBG] [tor]:  23 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:03:06.269 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 25; recommendation warn; host D349E0A7C940A16FACEEE8BB932CB732ED4619C7 at 46.38.237.49:9001)
> 2024-12-22 01:03:06.269 +03:00 [DBG] [tor]: 24 connections have failed:
> 2024-12-22 01:03:06.269 +03:00 [DBG] [tor]:  24 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:03:38.417 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 26; recommendation warn; host FEEBABA2B6FAF53AE1DC8DDA8681CE026537DFA4 at 185.229.90.81:993)
> 2024-12-22 01:03:38.417 +03:00 [DBG] [tor]: 25 connections have failed:
> 2024-12-22 01:03:38.417 +03:00 [DBG] [tor]:  25 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:03:44.461 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 27; recommendation warn; host 24E2F139121D4394C54B5BCC368B3B411857C413 at 204.13.164.118:443)
> 2024-12-22 01:03:44.461 +03:00 [DBG] [tor]: 26 connections have failed:
> 2024-12-22 01:03:44.461 +03:00 [DBG] [tor]:  26 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:04:02.532 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 28; recommendation warn; host 2B34099ED2BC598C4745C96C873FD73A445646BD at 185.82.219.109:443)
> 2024-12-22 01:04:02.533 +03:00 [DBG] [tor]: 27 connections have failed:
> 2024-12-22 01:04:02.533 +03:00 [DBG] [tor]:  27 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:04:31.604 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 29; recommendation warn; host BD6A829255CB08E66FBE7D3748363586E46B3810 at 171.25.193.9:80)
> 2024-12-22 01:04:31.605 +03:00 [DBG] [tor]: 28 connections have failed:
> 2024-12-22 01:04:31.605 +03:00 [DBG] [tor]:  28 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:04:42.661 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 30; recommendation warn; host 2B3AAC97B269D59E6D642C8BFB174EDD13741C38 at 199.195.253.156:9000)
> 2024-12-22 01:04:42.662 +03:00 [DBG] [tor]: 29 connections have failed:
> 2024-12-22 01:04:42.662 +03:00 [DBG] [tor]:  29 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:05:19.799 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 31; recommendation warn; host B9208EAD1E688E9EE43A05159ACD4638EB4DFD8A at 140.78.100.16:8443)
> 2024-12-22 01:05:19.800 +03:00 [DBG] [tor]: 30 connections have failed:
> 2024-12-22 01:05:19.800 +03:00 [DBG] [tor]:  30 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:05:25.821 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 32; recommendation warn; host F05114B22E66D08581B5936C646F62649485D879 at 85.214.202.158:9001)
> 2024-12-22 01:05:25.821 +03:00 [DBG] [tor]: 31 connections have failed:
> 2024-12-22 01:05:25.821 +03:00 [DBG] [tor]:  31 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:05:34.890 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 33; recommendation warn; host FAA4BCA4A6AC0FB4CA2F8AD5A11D9E122BA894F6 at 217.196.147.77:443)
> 2024-12-22 01:05:34.891 +03:00 [DBG] [tor]: 32 connections have failed:
> 2024-12-22 01:05:34.891 +03:00 [DBG] [tor]:  32 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:05:40.860 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 34; recommendation warn; host 1F43C824C1561935D22FA45CB87BDF8DD2E70B05 at 85.215.34.3:443)
> 2024-12-22 01:05:40.861 +03:00 [DBG] [tor]: 33 connections have failed:
> 2024-12-22 01:05:40.861 +03:00 [DBG] [tor]:  33 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:05:56.957 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 35; recommendation warn; host 5DC40F5357EDF4809A9010828172072C95A73514 at 146.0.40.193:9001)
> 2024-12-22 01:05:56.957 +03:00 [DBG] [tor]: 34 connections have failed:
> 2024-12-22 01:05:56.957 +03:00 [DBG] [tor]:  34 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:06:17.996 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 36; recommendation warn; host 8BF4E024210FF5DB1D7A4AFEBE11B48C73BFE779 at 92.205.129.7:21)
> 2024-12-22 01:06:17.997 +03:00 [DBG] [tor]: 35 connections have failed:
> 2024-12-22 01:06:17.997 +03:00 [DBG] [tor]:  35 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:07:19.316 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 37; recommendation warn; host B1D9038B9D4E56D1AC5CFE2D3B5FE4A2EA006BC6 at 193.26.115.43:8430)
> 2024-12-22 01:07:19.317 +03:00 [DBG] [tor]: 36 connections have failed:
> 2024-12-22 01:07:19.317 +03:00 [DBG] [tor]:  36 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:07:42.467 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 38; recommendation warn; host E3E42D35F801C9D5AB23584E0025D56FE2B33396 at 216.218.219.41:443)
> 2024-12-22 01:07:42.467 +03:00 [DBG] [tor]: 37 connections have failed:
> 2024-12-22 01:07:42.467 +03:00 [DBG] [tor]:  37 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:09:04.815 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 39; recommendation warn; host FAA4BCA4A6AC0FB4CA2F8AD5A11D9E122BA894F6 at 217.196.147.77:443)
> 2024-12-22 01:09:04.815 +03:00 [DBG] [tor]: 38 connections have failed:
> 2024-12-22 01:09:04.815 +03:00 [DBG] [tor]:  38 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:09:39.933 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 40; recommendation warn; host BD6A829255CB08E66FBE7D3748363586E46B3810 at 171.25.193.9:80)
> 2024-12-22 01:09:39.933 +03:00 [DBG] [tor]: 39 connections have failed:
> 2024-12-22 01:09:39.934 +03:00 [DBG] [tor]:  39 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:09:48.965 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 41; recommendation warn; host 302FEB0025AD49D2536B322C0A4C5F32F8322518 at 103.252.88.80:9400)
> 2024-12-22 01:09:48.966 +03:00 [DBG] [tor]: 40 connections have failed:
> 2024-12-22 01:09:48.966 +03:00 [DBG] [tor]:  40 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:10:16.098 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 42; recommendation warn; host 24E2F139121D4394C54B5BCC368B3B411857C413 at 204.13.164.118:443)
> 2024-12-22 01:10:16.098 +03:00 [DBG] [tor]: 41 connections have failed:
> 2024-12-22 01:10:16.098 +03:00 [DBG] [tor]:  41 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:11:15.404 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 43; recommendation warn; host 1A25C6358DB91342AA51720A5038B72742732498 at 128.31.0.39:9201)
> 2024-12-22 01:11:15.404 +03:00 [DBG] [tor]: 42 connections have failed:
> 2024-12-22 01:11:15.404 +03:00 [DBG] [tor]:  42 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:12:34.632 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 44; recommendation warn; host E3E42D35F801C9D5AB23584E0025D56FE2B33396 at 216.218.219.41:443)
> 2024-12-22 01:12:34.632 +03:00 [DBG] [tor]: 43 connections have failed:
> 2024-12-22 01:12:34.632 +03:00 [DBG] [tor]:  43 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:13:54.970 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 45; recommendation warn; host 7E1E7281107AF03B4C2C8744C7F82F2924311316 at 192.211.48.226:443)
> 2024-12-22 01:13:54.970 +03:00 [DBG] [tor]: 44 connections have failed:
> 2024-12-22 01:13:54.970 +03:00 [DBG] [tor]:  44 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:15:50.466 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 46; recommendation warn; host F2044413DAC2E02E3D6BCF4735A19BCA1DE97281 at 131.188.40.189:443)
> 2024-12-22 01:15:50.467 +03:00 [DBG] [tor]: 45 connections have failed:
> 2024-12-22 01:15:50.467 +03:00 [DBG] [tor]:  45 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:20:02.654 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 47; recommendation warn; host 9FFA1EE7FE653F9DA073925BDE299A74DCAC7595 at 107.189.14.43:26453)
> 2024-12-22 01:20:02.654 +03:00 [DBG] [tor]: 46 connections have failed:
> 2024-12-22 01:20:02.654 +03:00 [DBG] [tor]:  46 connections died in state connect()ing with SSL state (No SSL object)
> 2024-12-22 01:23:24.535 +03:00 [DBG] [tor]: Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 48; recommendation warn; host 74A910646BCEEFBCD2E874FC1DC997430F968145 at 199.58.81.140:443)
> 2024-12-22 01:23:24.535 +03:00 [DBG] [tor]: 47 connections have failed:
> 2024-12-22 01:23:24.535 +03:00 [DBG] [tor]:  47 connections died in state connect()ing with SSL state (No SSL object)

Maybe I should use bridges? As far as I know, some bridges (all obfs4) have been blocked in my country, but I can find some working.
Thank you for your responsiveness!

**Comment by aspriddell** [comment]
If you are residing in a country that doesn't have direct access to tor servers (i.e they're blocked) then yes you will need to configure bridges.

Snowflake and meek don't need any configuration, you can select them and connect. obfs4 and webtubnel bridges are available from the tor website (I think you can email them for lines if the site is blocked)

The log you uploaded suggests that it is struggling to make a valid connection which is an indication that either your system clock is wrong or something is trying to block connection to the tor relays (think content filtering system replacing the site with an access denied page). As you said you checked the clock it is more likely the latter.

Try using some bridges - if it doesn't work we can go from there.

**Comment by ZdenekBachy** [comment]
Thank you! I really stupid. I've been using TOR for a year now, but didn't guess bridges at once. 
I think there will soon be more people like me here. I can’t advise you, but send them straight away to look for bridges - it’s no secret that in East obfs, meek, snowflake can working really bad.
Thank for your attention again!
